
import React, { useState } from 'react';
import { FraudCase, KnowledgeSnippet, RedFlag, DetectionMethods, Finding, AuditProcedure } from '../types';
import { BookmarkIcon, LightbulbIcon, PencilIcon, PlusIcon, TrashIcon, CheckCircleSolidIcon, ErrorIcon, ShieldExclamationIcon, ArrowDownIcon } from './icons';
import { useProject } from '../contexts/ProjectContext';
import { useGlobal } from '../contexts/GlobalContext';
import { useUI } from '../contexts/UIContext';

// Import local icons for specific use here if needed, or map existing
const ShieldCheckIcon = CheckCircleSolidIcon; // Reusing check circle as safe shield

interface EditableFraudCaseProps {
    fraudCase: FraudCase;
    onSave: (updatedCase: FraudCase) => void;
    onCancel: () => void;
}

const EditableFraudCase: React.FC<EditableFraudCaseProps> = ({ fraudCase, onSave, onCancel }) => {
    // 深度防御：确保初始化编辑器时所有嵌套字段都存在，避免受控组件崩溃
    const [editedCase, setEditedCase] = useState<FraudCase>({
        ...fraudCase,
        scenario: fraudCase?.scenario || '',
        potentialActors: fraudCase?.potentialActors || '',
        fraudTriangle: {
            pressure: fraudCase?.fraudTriangle?.pressure || '',
            opportunity: fraudCase?.fraudTriangle?.opportunity || '',
            rationalization: fraudCase?.fraudTriangle?.rationalization || ''
        },
        redFlags: Array.isArray(fraudCase?.redFlags) ? fraudCase.redFlags : [],
        detectionMethods: {
            dataAnalytics: Array.isArray(fraudCase?.detectionMethods?.dataAnalytics) ? fraudCase.detectionMethods.dataAnalytics : [],
            documentReview: Array.isArray(fraudCase?.detectionMethods?.documentReview) ? fraudCase.detectionMethods.documentReview : [],
            inquiry: Array.isArray(fraudCase?.detectionMethods?.inquiry) ? fraudCase.detectionMethods.inquiry : [],
            observation: Array.isArray(fraudCase?.detectionMethods?.observation) ? fraudCase.detectionMethods.observation : []
        },
        // Preserve gapAnalysis if it exists, but not editable for now (generated by Judge)
        gapAnalysis: fraudCase.gapAnalysis
    });

    const handleChange = (field: keyof FraudCase, value: any) => {
        setEditedCase(prev => ({ ...prev, [field]: value }));
    };
    
    const handleTriangleChange = (field: keyof FraudCase['fraudTriangle'], value: string) => {
        setEditedCase(prev => ({ 
            ...prev, 
            fraudTriangle: { ...prev.fraudTriangle, [field]: value } 
        }));
    };

    const handleRedFlagChange = (index: number, field: keyof RedFlag, value: string) => {
        const updatedFlags = [...editedCase.redFlags];
        updatedFlags[index] = { ...updatedFlags[index], [field]: value };
        handleChange('redFlags', updatedFlags);
    };

    const addRedFlag = () => {
        handleChange('redFlags', [...editedCase.redFlags, { indicator: '', metric: '', threshold: '' }]);
    };
    
    const removeRedFlag = (index: number) => {
        handleChange('redFlags', editedCase.redFlags.filter((_, i) => i !== index));
    };
    
    const handleDetectionMethodChange = (category: keyof DetectionMethods, value: string) => {
        const methods = { 
            ...editedCase.detectionMethods, 
            [category]: value.split('\n').filter(line => line.trim() !== '') 
        };
        handleChange('detectionMethods', methods);
    };

    return (
        <div className="bg-yellow-50 shadow-md rounded-lg p-6 border border-yellow-300 relative space-y-4 animate-fade-in">
            <div>
                <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">案例场景</label>
                <textarea value={editedCase.scenario} onChange={e => handleChange('scenario', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-20 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" />
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                    <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">舞弊三角 - 压力</label>
                    <textarea value={editedCase.fraudTriangle.pressure} onChange={e => handleTriangleChange('pressure', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-24 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" />
                </div>
                <div>
                    <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">舞弊三角 - 机会</label>
                    <textarea value={editedCase.fraudTriangle.opportunity} onChange={e => handleTriangleChange('opportunity', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-24 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" />
                </div>
                <div>
                    <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">舞弊三角 - 借口</label>
                    <textarea value={editedCase.fraudTriangle.rationalization} onChange={e => handleTriangleChange('rationalization', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-24 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" />
                </div>
            </div>
            
            <div>
                <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">关键参与者</label>
                <input value={editedCase.potentialActors} onChange={e => handleChange('potentialActors', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" />
            </div>
            
            <div>
                 <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider mb-2 block">危险信号 (Red Flags)</label>
                 <div className="space-y-2">
                    {editedCase.redFlags.map((flag, index) => (
                        <div key={index} className="grid grid-cols-1 md:grid-cols-7 gap-2 items-center">
                            <input type="text" placeholder="指标" value={flag.indicator} onChange={e => handleRedFlagChange(index, 'indicator', e.target.value)} className="md:col-span-2 w-full p-1.5 border rounded text-xs" />
                            <input type="text" placeholder="量化方式" value={flag.metric} onChange={e => handleRedFlagChange(index, 'metric', e.target.value)} className="md:col-span-3 w-full p-1.5 border rounded text-xs" />
                            <input type="text" placeholder="阈值" value={flag.threshold} onChange={e => handleRedFlagChange(index, 'threshold', e.target.value)} className="md:col-span-1 w-full p-1.5 border rounded text-xs" />
                            <button onClick={() => removeRedFlag(index)} className="p-1.5 text-red-500 hover:bg-red-100 rounded-full justify-self-center"><TrashIcon className="h-4 w-4" /></button>
                        </div>
                    ))}
                 </div>
                 <button onClick={addRedFlag} className="mt-2 flex items-center gap-1 text-xs text-blue-600 hover:text-blue-800 font-semibold"><PlusIcon className="h-4 w-4" />添加信号</button>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                    <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">侦测方法 - 数据分析</label>
                    <textarea value={editedCase.detectionMethods.dataAnalytics.join('\n')} onChange={e => handleDetectionMethodChange('dataAnalytics', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-24 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" placeholder="每行一个方法..." />
                </div>
                <div>
                    <label className="text-xs font-bold text-yellow-800 uppercase tracking-wider">侦测方法 - 文档审阅</label>
                    <textarea value={editedCase.detectionMethods.documentReview.join('\n')} onChange={e => handleDetectionMethodChange('documentReview', e.target.value)} className="w-full p-2 border border-yellow-200 rounded mt-1 h-24 text-sm focus:ring-2 focus:ring-yellow-400 focus:outline-none" placeholder="每行一个方法..." />
                </div>
            </div>

            <div className="flex justify-end gap-3 pt-4 border-t border-yellow-200">
                <button onClick={onCancel} className="px-4 py-2 bg-white border border-yellow-300 text-yellow-800 text-sm font-medium rounded hover:bg-yellow-100 transition-colors">取消</button>
                <button onClick={() => onSave(editedCase)} className="px-6 py-2 bg-yellow-600 text-white text-sm font-bold rounded hover:bg-yellow-700 shadow-md transition-colors">保存案例</button>
            </div>
        </div>
    )
}

export const FraudAnalysisPanel: React.FC = () => {
  const { activeProjectState, handleToggleSnippet, handleUpdateFraudCases, handleUpdateProgram } = useProject();
  const { globalState } = useGlobal();
  const { selectedItemId, setSelectedItemId, setNotification } = useUI();
  const [editingIndex, setEditingIndex] = useState<number | null>(null);

  const activeProgram = activeProjectState.auditPrograms.find(p => p.id === activeProjectState.activeProgramId) || null;
  const cases = activeProgram ? activeProjectState.fraudAnalyses[activeProgram.id] || [] : [];
  const programId = activeProgram?.id || null;
  const snippets = globalState.snippets;

  if (!cases || cases.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center text-gray-500 p-8">
        <div className="w-20 h-20 bg-yellow-50 rounded-full flex items-center justify-center mb-6">
            <LightbulbIcon className="h-10 w-10 text-yellow-300" />
        </div>
        <h2 className="text-xl font-bold text-gray-800">舞弊风险头脑风暴</h2>
        <p className="mt-2 text-sm max-w-sm text-gray-500">
          目前尚未针对此程序生成舞弊分析。请在左侧对话框中点击“舞弊风险分析”按钮。
        </p>
      </div>
    );
  }

  const handleToggleCaseSnippet = (fraudCase: FraudCase, sourceId: string) => {
    // FIX: Optimized defensive programming by using optional chaining on triangle and detectionMethods
    // This avoids TypeScript errors when triangle or dMethods are undefined/null
    const triangle = fraudCase?.fraudTriangle;
    const dMethods = fraudCase?.detectionMethods;
    
    const content = `| 舞弊场景 | 舞弊三角因素 | 侦测审计方法 |
|:---|:---|:---|
| ${fraudCase.scenario || '未定义'} | **压力**: ${triangle?.pressure || 'N/A'}<br/>**机会**: ${triangle?.opportunity || 'N/A'}<br/>**借口**: ${triangle?.rationalization || 'N/A'} | ${[...(dMethods?.dataAnalytics || []), ...(dMethods?.documentReview || [])].join('<br/>') || '未指定'} |`;

    handleToggleSnippet({ sourceId, content, type: "舞弊案例分析" });
  };

  const handleSaveEdit = (updatedCase: FraudCase) => {
    if (editingIndex !== null && programId) {
        const updatedCases = [...cases];
        updatedCases[editingIndex] = updatedCase;
        handleUpdateFraudCases(programId, updatedCases);
        setEditingIndex(null);
    }
  };

  const handleAddProcedure = (fraudCase: FraudCase) => {
      if (!fraudCase.gapAnalysis?.suggestedProcedure || !activeProgram) return;
      
      const suggestion = fraudCase.gapAnalysis.suggestedProcedure;
      const newProcedure: AuditProcedure = {
          id: `AP-${Date.now().toString().slice(-4)}`,
          risk: suggestion.risk,
          riskLevel: '高', // Default to High for fraud risks
          control: suggestion.control,
          testStep: suggestion.testStep
      };
      
      const updatedProcedures = [...activeProgram.procedures, newProcedure];
      handleUpdateProgram(activeProgram, updatedProcedures);
      
      // OPTIONAL: Update the local fraud case status to reflect it's been addressed? 
      // For now, we just notify.
      setNotification({ message: '已成功将补救程序添加到审计方案中。', type: 'success' });
  };

  return (
    <div className="p-4 sm:p-8 max-w-5xl mx-auto space-y-6">
      <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 rounded-r-lg mb-8">
          <p className="text-sm text-yellow-800 font-medium">
              基于 **舞弊三角理论 (Fraud Triangle)** 识别的潜在风险点。AI 旨在挑战现有控制环境，帮助识别管理层凌驾于控制之上的可能性。
          </p>
      </div>

      {cases.map((fraudCase, index) => {
        const sourceId = `${programId}-fraud-${index}`;
        const isSaved = snippets.some(s => s.sourceId === sourceId);
        const isSelected = selectedItemId === `fraud-${index}`;
        const gap = fraudCase.gapAnalysis;
        const isExposed = gap && (gap.status === 'EXPOSED' || gap.status === 'PARTIALLY_COVERED');

        return editingIndex === index ? (
            <EditableFraudCase 
                key={`edit-${index}`}
                fraudCase={fraudCase}
                onSave={handleSaveEdit}
                onCancel={() => setEditingIndex(null)}
            />
        ) : (
        <div 
          key={index} 
          onClick={() => setSelectedItemId(`fraud-${index}`)}
          className={`bg-white shadow-sm rounded-xl p-6 border-2 transition-all duration-300 group relative ${isSelected ? 'border-yellow-400 ring-4 ring-yellow-50 scale-[1.02]' : 'border-gray-100 hover:border-yellow-200 hover:shadow-md'}`}
        >
          {/* Header Status Badge */}
          <div className="flex justify-between items-start mb-4">
              <div className="flex items-center gap-3">
                  {isExposed ? (
                      <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-red-100 text-red-700 text-xs font-bold border border-red-200">
                          <ErrorIcon className="h-3.5 w-3.5" />
                          风险敞口 (EXPOSED)
                      </span>
                  ) : (
                      <span className="flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-green-100 text-green-700 text-xs font-bold border border-green-200">
                          <ShieldCheckIcon className="h-3.5 w-3.5" />
                          已覆盖 (COVERED)
                      </span>
                  )}
                  <h3 className="m-0 font-bold text-gray-900 leading-tight text-base">
                      {fraudCase.scenario || '未定义场景'}
                  </h3>
              </div>
              
              <div className="flex gap-2">
                <button
                    onClick={(e) => { e.stopPropagation(); setEditingIndex(index); }}
                    className="p-2 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity text-gray-400 hover:text-yellow-600 hover:bg-yellow-50"
                    title="编辑此案例"
                >
                    <PencilIcon className="h-5 w-5" />
                </button>
                <button
                    onClick={(e) => { e.stopPropagation(); handleToggleCaseSnippet(fraudCase, sourceId); }}
                    className={`p-2 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity ${isSaved ? 'text-orange-500 bg-orange-50' : 'text-gray-400 hover:text-blue-500 hover:bg-blue-50'}`}
                    title={isSaved ? "从知识库移除" : "收藏至知识库"}
                >
                    <BookmarkIcon className="h-5 w-5" />
                </button>
              </div>
          </div>

          <div className="prose prose-sm max-w-none">
            
            {/* Gap Analysis Section (New) */}
            {gap && (
                <div className={`p-4 rounded-lg mb-6 border ${isExposed ? 'bg-red-50 border-red-100' : 'bg-green-50 border-green-100'}`}>
                    <h5 className={`mt-0 mb-2 text-xs font-bold uppercase tracking-wider flex items-center gap-2 ${isExposed ? 'text-red-800' : 'text-green-800'}`}>
                        {isExposed ? <ErrorIcon className="h-4 w-4"/> : <ShieldCheckIcon className="h-4 w-4"/>}
                        现有防御评估 (Gap Analysis)
                    </h5>
                    <p className={`text-sm leading-relaxed mb-0 ${isExposed ? 'text-red-700' : 'text-green-700'}`}>
                        {gap.assessment}
                    </p>
                    
                    {/* Remediation Action */}
                    {isExposed && gap.suggestedProcedure && (
                        <div className="mt-4 pt-3 border-t border-red-200">
                            <h6 className="text-xs font-bold text-red-800 mb-2 flex items-center gap-1">
                                <LightbulbIcon className="h-3.5 w-3.5" /> 建议补救程序
                            </h6>
                            <div className="bg-white p-3 rounded border border-red-200 text-xs text-slate-600 space-y-1">
                                <p><strong>风险:</strong> {gap.suggestedProcedure.risk}</p>
                                <p><strong>控制:</strong> {gap.suggestedProcedure.control}</p>
                                <p><strong>测试:</strong> {gap.suggestedProcedure.testStep}</p>
                            </div>
                            <button 
                                onClick={(e) => { e.stopPropagation(); handleAddProcedure(fraudCase); }}
                                className="mt-3 flex items-center gap-2 px-3 py-1.5 bg-red-600 text-white text-xs font-bold rounded hover:bg-red-700 shadow-sm transition-colors"
                            >
                                <PlusIcon className="h-3.5 w-3.5" />
                                添加到审计程序
                            </button>
                        </div>
                    )}
                </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 my-6">
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100">
                    <h5 className="mt-0 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">🚩 压力 / 动机</h5>
                    <p className="text-gray-700 leading-relaxed text-xs">{fraudCase.fraudTriangle?.pressure || <span className="text-gray-300 italic">未识别特定压力点</span>}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100">
                    <h5 className="mt-0 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">🔓 机会因子</h5>
                    <p className="text-gray-700 leading-relaxed text-xs">{fraudCase.fraudTriangle?.opportunity || <span className="text-gray-300 italic">未识别控制漏洞</span>}</p>
                </div>
                <div className="bg-slate-50 p-4 rounded-lg border border-slate-100">
                    <h5 className="mt-0 mb-2 text-xs font-bold text-slate-500 uppercase tracking-wider">🎭 合理化借口</h5>
                    <p className="text-gray-700 leading-relaxed text-xs">{fraudCase.fraudTriangle?.rationalization || <span className="text-gray-300 italic">未识别心理特征</span>}</p>
                </div>
            </div>

            <div className="space-y-6">
                <div>
                    <h5 className="font-bold text-gray-800 text-sm flex items-center gap-2 mb-2"><span className="w-1.5 h-4 bg-red-400 rounded-full"></span> 危险信号 (Red Flags)</h5>
                    <div className="overflow-hidden rounded-lg border border-gray-100 shadow-sm">
                        <table className="min-w-full text-xs">
                            <thead className="bg-gray-50 border-b border-gray-100">
                                <tr>
                                    <th className="px-4 py-2 text-left font-semibold text-gray-600">异常指标</th>
                                    <th className="px-4 py-2 text-left font-semibold text-gray-600">量化方式</th>
                                    <th className="px-4 py-2 text-left font-semibold text-gray-600">预警阈值</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-50 text-gray-700">
                                {(fraudCase.redFlags || []).length > 0 ? (fraudCase.redFlags || []).map((flag, i) => (
                                    <tr key={i} className="hover:bg-gray-50/50">
                                        <td className="px-4 py-2.5 font-medium">{flag.indicator || 'N/A'}</td>
                                        <td className="px-4 py-2.5">{flag.metric || 'N/A'}</td>
                                        <td className="px-4 py-2.5 font-mono text-red-600">{flag.threshold || 'N/A'}</td>
                                    </tr>
                                )) : (
                                    <tr><td colSpan={3} className="px-4 py-6 text-center text-gray-400 italic">模型未识别到具体可量化的指标</td></tr>
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-gray-50">
                    <div>
                        <h5 className="font-bold text-gray-800 text-sm flex items-center gap-2 mb-3">🔍 数据挖掘方法</h5>
                        <ul className="list-none p-0 m-0 space-y-2">
                            {(fraudCase.detectionMethods?.dataAnalytics || []).map((method, i) => (
                                <li key={i} className="text-xs text-gray-600 flex items-start gap-2">
                                    <span className="text-blue-500 mt-0.5">•</span>
                                    {method}
                                </li>
                            ))}
                            {(!fraudCase.detectionMethods?.dataAnalytics?.length) && <li className="text-gray-400 italic text-xs">暂无推荐</li>}
                        </ul>
                    </div>
                    <div>
                        <h5 className="font-bold text-gray-800 text-sm flex items-center gap-2 mb-3">📋 文档核查清单</h5>
                        <ul className="list-none p-0 m-0 space-y-2">
                            {(fraudCase.detectionMethods?.documentReview || []).map((method, i) => (
                                <li key={i} className="text-xs text-gray-600 flex items-start gap-2">
                                    <span className="text-green-500 mt-0.5">•</span>
                                    {method}
                                </li>
                            ))}
                            {(!fraudCase.detectionMethods?.documentReview?.length) && <li className="text-gray-400 italic text-xs">暂无推荐</li>}
                        </ul>
                    </div>
                </div>
            </div>
          </div>
        </div>
        )
      })}
    </div>
  );
};
